- hosts: "awx"
# remote_user: "{{ ssh_user }}"
  remote_user: root
  become: yes

  vars:
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-py

  roles:
    - geerlingguy.repo-epel  #  (role fixed. se puede obviar pre-registrando el repo epel)
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx

  tasks:
    - pip:
        name: ansible-tower-cli
        state: latest
    - shell: tower-cli config host http://"{{ ansible_host }}":80
    - shell: tower-cli config username admin
    - shell: tower-cli config password password
    - shell: tower-cli config verify_ssl false
#    - shell: tower-cli user list
